<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-28T16:33:36 IST" name="Default suite" finished-at="2024-10-28T16:33:50 IST" duration-ms="13709">
    <groups>
    </groups>
    <test started-at="2024-10-28T16:33:36 IST" name="Default test" finished-at="2024-10-28T16:33:50 IST" duration-ms="13709">
      <class name="playwright.firstTest.Reports">
        <test-method is-config="true" signature="setReport()[pri:0, instance:playwright.firstTest.Reports@5542c4ed]" started-at="2024-10-28T16:33:36 IST" name="setReport" finished-at="2024-10-28T16:33:41 IST" duration-ms="4314" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setReport -->
        <test-method signature="doLogin()[pri:0, instance:playwright.firstTest.Reports@5542c4ed]" started-at="2024-10-28T16:33:41 IST" name="doLogin" finished-at="2024-10-28T16:33:45 IST" duration-ms="4664" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Login failed, notification displayed.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Login failed, notification displayed.
at playwright.firstTest.Reports.doLogin(Reports.java:91)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method is-config="true" signature="updateResults(org.testng.ITestResult)[pri:0, instance:playwright.firstTest.Reports@5542c4ed]" started-at="2024-10-28T16:33:45 IST" name="updateResults" finished-at="2024-10-28T16:33:45 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLogin status=FAILURE method=Reports.doLogin()[pri:0, instance:playwright.firstTest.Reports@5542c4ed] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateResults -->
        <test-method signature="navigateToDashboard()[pri:0, instance:playwright.firstTest.Reports@5542c4ed]" started-at="2024-10-28T16:33:45 IST" name="navigateToDashboard" finished-at="2024-10-28T16:33:45 IST" depends-on-methods="playwright.firstTest.Reports.doLogin" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method playwright.firstTest.Reports.navigateToDashboard() on instance playwright.firstTest.Reports@5542c4ed depends on not successfully finished methods 
[playwright.firstTest.Reports.doLogin() on instance playwright.firstTest.Reports@5542c4ed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method playwright.firstTest.Reports.navigateToDashboard() on instance playwright.firstTest.Reports@5542c4ed depends on not successfully finished methods 
[playwright.firstTest.Reports.doLogin() on instance playwright.firstTest.Reports@5542c4ed]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToDashboard -->
        <test-method signature="placeBid()[pri:0, instance:playwright.firstTest.Reports@5542c4ed]" started-at="2024-10-28T16:33:45 IST" name="placeBid" finished-at="2024-10-28T16:33:45 IST" depends-on-methods="playwright.firstTest.Reports.navigateToDashboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method playwright.firstTest.Reports.placeBid() on instance playwright.firstTest.Reports@5542c4ed depends on not successfully finished methods 
[playwright.firstTest.Reports.navigateToDashboard() on instance playwright.firstTest.Reports@5542c4ed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method playwright.firstTest.Reports.placeBid() on instance playwright.firstTest.Reports@5542c4ed depends on not successfully finished methods 
[playwright.firstTest.Reports.navigateToDashboard() on instance playwright.firstTest.Reports@5542c4ed]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeBid -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:playwright.firstTest.Reports@5542c4ed]" started-at="2024-10-28T16:33:45 IST" name="endReport" finished-at="2024-10-28T16:33:50 IST" duration-ms="4690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- playwright.firstTest.Reports -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
